### PR TITLE
Workerz

### PR DESCRIPTION
**Pull request by film42**
This is the first pass at getting a repeatable worker running within the django project. Instead of adding RabbitMQ, we're just going to use the local DB broker to make development easier for everyone.

Now, when you run `honcho start`, you will see that an additional celery process starts. These celery tasks are defined under `exchange/tasks.py`. I added a `schedule_task` method, so you can add a repeatable task anywhere in the code (though it's kind of a hack).

Also, this PR cleans up the settings because they were WAY messed up.

**ATTENTION**

You WILL need to do the following to keep developing:
1. Blow out your `settings.py` and copy it from `settings.py.sample`.
2. Migrate your database: `python manage.py syncdb`.

cc @reedcwilson @sgbench @marioagarcia @cdbelyeu

### CODE REVIEW

**Comment by reedcwilson** [comment]
So why do we need to have the ability to add repeating tasks?

**Comment by film42** [comment]
So we can check and update a user's trades as they are completed in a background thread.

**Comment by reedcwilson** [comment]
oh okay. Well it looks good to me. How do we create a task?

Is this the example?

```
# Schedule Tasks
schedule_task(
    'add-every-30-seconds', {
        'task': 'exchange.tasks.add',
        'schedule': timedelta(seconds=30),
        'args': (16, 16)
    }
)
```

**Comment by film42** [comment]
Yup. That's the current way of doing it. It basically injects that hash into celery's settings.

**Comment by reedcwilson** [comment]
Sweet. :shipit:

**Pull request merged**
