### PR TITLE
Endpoint tests

### PR DESCRIPTION
**Pull request by cdbelyeu**
wrote some unit tests for the rest api. Fixed one bug in the views (incorrect queryset), and redid migrations, which were broken after our work on the Users model last week.

### CODE REVIEW

**Comment by film42** [comment]
Travis is saying, `Ran 0 tests in 0.000s`. Did you switch to the new settings.py when you were testing? We're putting all application specific stuff in it's own settings file.

**Comment by cdbelyeu** [comment]
Travis is fixed!

**Comment by film42** [comment]
Could you write a short comment on what was wrong so we can fix it if it happens again? Do that and then :shipit: !!

**Comment by cdbelyeu** [comment]
Since we were testing a couple of different things, I tried separating tests.py into several test files inside a test directory. This should theoretically work with the django test runner, and it worked in my local branch, but not when I pushed it up. In the long run, we will probably need to break up the tests, but in the short term, I put them all back into a single source file. Everything should now work with Travis

**Pull request merged**
